"""Algo Connector — Public endpoints for external algo bots.

POST /api/algo/trade   — BUY / SELL / CLOSE
GET  /api/algo/account — balance, equity, margin, leverage

Auth: X-Api-Key + X-Api-Secret headers (per-account keys generated by users).
"""
import hashlib
import json
import logging
from datetime import datetime, timezone
from decimal import Decimal
from uuid import UUID

from fastapi import APIRouter, HTTPException, Header
from pydantic import BaseModel, Field
from sqlalchemy import select, update, func
from typing import Optional

from packages.common.src.config import get_settings
from packages.common.src.database import AsyncSessionLocal
from packages.common.src.ib_commission import distribute_ib_commission
from packages.common.src.instrument_pricing import resolve_commission, resolve_user_quote
from packages.common.src.market_hours import is_market_open
from packages.common.src.models import (
    AlgoApiKey, TradingAccount, Instrument, InstrumentConfig,
    Position, PositionStatus, Order, TradeHistory, Transaction,
)
from packages.common.src.redis_client import redis_client, PriceChannel, is_tick_stale

logger = logging.getLogger("algo_connector")
router = APIRouter()


def _hash_secret(raw: str) -> str:
    """SHA-256 hash for fast lookup (bcrypt is overkill for API secrets)."""
    return hashlib.sha256(raw.encode()).hexdigest()


class AlgoTradeRequest(BaseModel):
    action: str = Field(..., pattern="^(BUY|SELL|CLOSE)$")
    symbol: str
    volume: Optional[float] = None
    sl: Optional[float] = None
    tp: Optional[float] = None
    comment: Optional[str] = None


@router.post("/trade")
async def algo_trade(
    body: AlgoTradeRequest,
    x_api_key: str = Header(default="", alias="X-Api-Key"),
    x_api_secret: str = Header(default="", alias="X-Api-Secret"),
):
    if not x_api_key or not x_api_secret:
        raise HTTPException(status_code=401, detail="Missing X-Api-Key or X-Api-Secret")

    secret_hash = _hash_secret(x_api_secret)

    async with AsyncSessionLocal() as db:
        result = await db.execute(
            select(AlgoApiKey).where(
                AlgoApiKey.api_key == x_api_key,
                AlgoApiKey.is_active == True,
            )
        )
        key_row = result.scalar_one_or_none()

        if not key_row or key_row.secret_hash != secret_hash:
            raise HTTPException(status_code=401, detail="Invalid API credentials")

        # Lock the account row — same fix as the web order path: two
        # concurrent bot orders must not both pass the margin check against
        # the same free_margin snapshot.
        account = await db.get(TradingAccount, key_row.account_id, with_for_update=True)
        if not account or not account.is_active:
            raise HTTPException(status_code=403, detail="Trading account is inactive")

        # Update last_used_at
        key_row.last_used_at = datetime.now(timezone.utc)

        symbol = body.symbol.upper()
        action = body.action.upper()

        if action in ("BUY", "SELL"):
            if not body.volume or body.volume <= 0:
                raise HTTPException(status_code=400, detail="volume required for BUY/SELL")
            result = await _open_trade(body, symbol, account, key_row, db)
        else:
            result = await _close_trades(symbol, account, key_row, db)

        await db.commit()
        return result


@router.get("/account")
async def algo_account(
    x_api_key: str = Header(default="", alias="X-Api-Key"),
    x_api_secret: str = Header(default="", alias="X-Api-Secret"),
):
    """Return balance, equity, margin and leverage for the linked trading account."""
    if not x_api_key or not x_api_secret:
        raise HTTPException(status_code=401, detail="Missing X-Api-Key or X-Api-Secret")

    secret_hash = _hash_secret(x_api_secret)

    async with AsyncSessionLocal() as db:
        key_q = await db.execute(
            select(AlgoApiKey).where(
                AlgoApiKey.api_key == x_api_key,
                AlgoApiKey.is_active == True,
            )
        )
        key_row = key_q.scalar_one_or_none()

        if not key_row or key_row.secret_hash != secret_hash:
            raise HTTPException(status_code=401, detail="Invalid API credentials")

        account = await db.get(TradingAccount, key_row.account_id)
        if not account or not account.is_active:
            raise HTTPException(status_code=403, detail="Trading account is inactive")

        key_row.last_used_at = datetime.now(timezone.utc)

        open_q = await db.execute(
            select(func.count(Position.id)).where(
                Position.account_id == account.id,
                Position.status == PositionStatus.OPEN,
            )
        )
        open_count = int(open_q.scalar() or 0)

        await db.commit()

        zero = Decimal("0")
        return {
            "account": account.account_number,
            "currency": account.currency or "USD",
            "leverage": int(account.leverage or 100),
            "balance": float(account.balance or zero),
            "credit": float(account.credit or zero),
            "equity": float(account.equity or zero),
            "margin_used": float(account.margin_used or zero),
            "free_margin": float(account.free_margin or zero),
            "margin_level": float(account.margin_level or zero),
            "is_demo": bool(account.is_demo),
            "open_positions": open_count,
        }


async def _open_trade(body: AlgoTradeRequest, symbol: str, account: TradingAccount, key_row: AlgoApiKey, db) -> dict:
    """Open a market order on the linked trading account."""
    inst_q = await db.execute(
        select(Instrument).where(Instrument.symbol == symbol, Instrument.is_active == True)
    )
    instrument = inst_q.scalar_one_or_none()
    if not instrument:
        raise HTTPException(status_code=404, detail=f"Instrument {symbol} not found")

    # Algo trades are market-only — enforce the same market-hours rule as the
    # web order path. Bots were previously able to fill against the frozen
    # weekend/holiday quote.
    segment_name = instrument.segment.name if instrument.segment else ""
    market_open, closed_reason = is_market_open(
        instrument.symbol, segment_name, instrument.trading_hours
    )
    if not market_open:
        raise HTTPException(
            status_code=400,
            detail=closed_reason or f"Market is closed for {symbol}",
        )

    # Per-instrument lot bounds + kill switch — same source as the web path
    # (InstrumentConfig overrides, Instrument defaults). The old hardcoded
    # 0.01 floor ignored admin-configured limits entirely.
    ic = (await db.execute(
        select(InstrumentConfig).where(InstrumentConfig.instrument_id == instrument.id)
    )).scalar_one_or_none()
    if ic and ic.is_enabled is False:
        raise HTTPException(status_code=400, detail=f"Trading disabled for {symbol}")
    min_lot = ic.min_lot_size if ic and ic.min_lot_size is not None else (instrument.min_lot or Decimal("0.01"))
    max_lot = ic.max_lot_size if ic and ic.max_lot_size is not None else (instrument.max_lot or Decimal("100"))

    lots = Decimal(str(body.volume))
    if lots < min_lot or lots > max_lot:
        raise HTTPException(status_code=400, detail=f"Lot size must be between {min_lot} and {max_lot}")

    tick_data = await redis_client.get(PriceChannel.tick_key(symbol))
    if not tick_data:
        raise HTTPException(status_code=400, detail=f"No price data for {symbol}")

    tick = json.loads(tick_data)
    # Same rule as every other execution path: a stale quote (dead feed /
    # refresher republish) must never fill a trade.
    if is_tick_stale(tick):
        raise HTTPException(
            status_code=400,
            detail=f"Market data for {symbol} is reconnecting — try again shortly",
        )
    bid = Decimal(str(tick["bid"]))
    ask = Decimal(str(tick["ask"]))

    # Per-user execution spread — identical to the web order path, so a bot
    # fill and a manual fill on the same account price identically.
    if get_settings().USER_SPREAD_AT_EXECUTION:
        try:
            bid, ask = await resolve_user_quote(
                db, instrument, bid, ask,
                user_id=account.user_id,
                account_group_id=account.account_group_id,
                trading_account_id=account.id,
            )
        except Exception as exc:
            logger.warning("[ALGO] user quote (open) failed for %s, using broadcast: %s", symbol, exc)

    side = body.action.lower()
    fill_price = ask if side == "buy" else bid
    contract_size = instrument.contract_size or Decimal("100000")
    required_margin = lots * contract_size * fill_price / Decimal(str(account.leverage))

    if required_margin > (account.free_margin or Decimal("0")):
        raise HTTPException(status_code=400, detail="Insufficient margin")

    # Same resolver as web/pending fills (ChargeConfig chain, tier defaults,
    # VIP discount). Hardcoding 0 here silently waived commission on every
    # bot trade — see ALGO_CONNECTOR_INTEGRATION.md invariants.
    commission = await resolve_commission(
        db, instrument, lots, fill_price,
        user_id=account.user_id,
        account_group_id=account.account_group_id,
    )

    sl = Decimal(str(body.sl)) if body.sl else None
    tp = Decimal(str(body.tp)) if body.tp else None

    order = Order(
        account_id=account.id,
        instrument_id=instrument.id,
        order_type="market",
        side=side,
        status="filled",
        lots=lots,
        filled_price=fill_price,
        filled_at=datetime.now(timezone.utc),
        stop_loss=sl,
        take_profit=tp,
        commission=commission,
        comment=body.comment or f"Algo [{key_row.label or key_row.api_key[:12]}]",
    )
    db.add(order)
    await db.flush()

    position = Position(
        account_id=account.id,
        instrument_id=instrument.id,
        order_id=order.id,
        side=side,
        status=PositionStatus.OPEN.value,
        lots=lots,
        open_price=fill_price,
        stop_loss=sl,
        take_profit=tp,
        commission=commission,
        comment=body.comment or f"Algo [{key_row.label or key_row.api_key[:12]}]",
    )
    db.add(position)
    await db.flush()

    account.margin_used = (account.margin_used or Decimal("0")) + required_margin
    account.balance = (account.balance or Decimal("0")) - commission
    account.equity = account.balance + (account.credit or Decimal("0"))
    account.free_margin = account.equity - account.margin_used
    key_row.trades_count = (key_row.trades_count or 0) + 1

    # A bot fill is a real trade — pay the IB chain exactly like web and
    # pending fills do. Best-effort: never block the fill on it.
    try:
        await distribute_ib_commission(db, account.user_id, order.id, lots, symbol)
    except Exception as exc:
        logger.error("[ALGO] IB commission distribution failed for order %s: %s", order.id, exc)

    # Nudge any open web terminal for this account — same channel the other
    # fill paths publish on. Best-effort.
    try:
        await redis_client.publish(f"account:{account.id}", json.dumps({
            "type": "order_update",
            "order_id": str(order.id),
            "source": "algo",
        }))
    except Exception:
        pass

    logger.info(
        "[ALGO] %s %s %.2f lots @ %s on %s (key=%s)",
        side.upper(), symbol, float(lots), fill_price,
        account.account_number, key_row.api_key[:12],
    )
    return {
        "status": "filled",
        "action": body.action,
        "symbol": symbol,
        "lots": float(lots),
        "price": float(fill_price),
        "position_id": str(position.id),
        "order_id": str(order.id),
        "account": account.account_number,
    }


async def _close_trades(symbol: str, account: TradingAccount, key_row: AlgoApiKey, db) -> dict:
    """Close all open positions for symbol on the account."""
    # SKIP LOCKED: a position mid-close by the SL/TP engine or a manual web
    # close is skipped instead of double-closed (double balance credit).
    pos_q = await db.execute(
        select(Position).join(Instrument).where(
            Position.account_id == account.id,
            Position.status == PositionStatus.OPEN,
            Instrument.symbol == symbol,
        ).with_for_update(skip_locked=True, of=Position)
    )
    positions = pos_q.scalars().all()

    if not positions:
        return {
            "status": "no_positions",
            "symbol": symbol,
            "account": account.account_number,
            "message": f"No open {symbol} positions to close",
        }

    tick_data = await redis_client.get(PriceChannel.tick_key(symbol))
    if not tick_data:
        raise HTTPException(status_code=400, detail=f"No price data for {symbol}")

    tick = json.loads(tick_data)
    # Never book a close at a frozen/refresher quote — same stale rule as the
    # web close path.
    if is_tick_stale(tick):
        raise HTTPException(
            status_code=400,
            detail=f"Market data for {symbol} is reconnecting — try again shortly",
        )
    c_bid = Decimal(str(tick["bid"]))
    c_ask = Decimal(str(tick["ask"]))

    closed_count = 0
    total_profit = Decimal("0")

    from packages.common.src.trading_service import quote_to_account_pnl, cross_rate_for

    for pos in positions:
        instrument = pos.instrument
        if not instrument:
            continue

        bid, ask = c_bid, c_ask
        # Per-user execution spread on the close leg too, so the spread is
        # crossed exactly once per round trip — mirrors trading_service.
        if get_settings().USER_SPREAD_AT_EXECUTION:
            try:
                bid, ask = await resolve_user_quote(
                    db, instrument, bid, ask,
                    user_id=account.user_id,
                    account_group_id=account.account_group_id,
                    trading_account_id=account.id,
                )
            except Exception as exc:
                logger.warning("[ALGO] user quote (close) failed for %s, using broadcast: %s", symbol, exc)

        sv = pos.side.value if hasattr(pos.side, "value") else str(pos.side)
        close_price = bid if sv == "buy" else ask
        contract_size = instrument.contract_size or Decimal("100000")

        if sv == "buy":
            profit = (close_price - pos.open_price) * pos.lots * contract_size
        else:
            profit = (pos.open_price - close_price) * pos.lots * contract_size
        profit = quote_to_account_pnl(
            profit,
            getattr(instrument, "base_currency", None),
            getattr(instrument, "quote_currency", None),
            close_price,
            symbol=getattr(instrument, "symbol", None),
            cross_rate=await cross_rate_for(instrument),
        )

        pos.status = PositionStatus.CLOSED.value
        pos.close_price = close_price
        pos.profit = profit
        pos.closed_at = datetime.now(timezone.utc)

        account.balance = (account.balance or Decimal("0")) + profit
        margin_release = (pos.lots * contract_size * pos.open_price) / Decimal(str(account.leverage))
        account.margin_used = max(Decimal("0"), (account.margin_used or Decimal("0")) - margin_release)
        account.equity = account.balance + (account.credit or Decimal("0"))
        account.free_margin = account.equity - account.margin_used

        db.add(TradeHistory(
            position_id=pos.id,
            account_id=pos.account_id,
            instrument_id=pos.instrument_id,
            side=pos.side,
            lots=pos.lots,
            open_price=pos.open_price,
            close_price=close_price,
            swap=pos.swap or Decimal("0"),
            commission=pos.commission or Decimal("0"),
            profit=profit,
            close_reason="algo_close",
            opened_at=pos.created_at,
            closed_at=datetime.now(timezone.utc),
        ))
        # Transactions ledger row — every other close path (manual, SL/TP,
        # stop-out) writes one; algo closes were invisible to statements.
        db.add(Transaction(
            user_id=account.user_id,
            account_id=account.id,
            type="profit" if profit >= 0 else "loss",
            amount=profit,
            balance_after=account.balance,
            reference_id=pos.id,
            description=f"Algo close: {symbol} {sv} {pos.lots} lots @ {close_price}",
        ))
        # Live update for any open web terminal — same shape as sltp_engine.
        try:
            await redis_client.publish(f"account:{account.id}", json.dumps({
                "type": "position_closed",
                "position_id": str(pos.id),
                "reason": "algo_close",
                "profit": str(profit),
                "close_price": str(close_price),
            }))
        except Exception:
            pass
        closed_count += 1
        total_profit += profit

    key_row.trades_count = (key_row.trades_count or 0) + closed_count

    logger.info("[ALGO] Closed %d %s positions on %s (P/L: %s)", closed_count, symbol, account.account_number, total_profit)
    return {
        "status": "closed",
        "symbol": symbol,
        "account": account.account_number,
        "closed_count": closed_count,
        "total_profit": float(total_profit),
    }
