"""Algo Connector — Public endpoints for external algo bots.

POST /api/algo/trade     — BUY / SELL / CLOSE (CLOSE takes an optional position_id)
GET  /api/algo/account   — balance, equity, margin, leverage
GET  /api/algo/positions — every open position on the linked account

Auth: X-Api-Key + X-Api-Secret headers (per-account keys generated by users).

Execution DELEGATES to trading_service.place_order / close_position — the same
code path as the web terminal. A previous version re-implemented open/close
inline here and silently diverged from the canonical path: zero commission, no
stale-tick guard, no market-hours or maintenance check, no account row lock
(over-leverage race), no Transaction ledger rows, no IB distribution, no bonus
release, no cross-rate P&L conversion, and no A-book forwarding. Any future
"algo needs different behavior" requirement must be expressed as parameters on
the canonical functions, never as a parallel implementation.
"""
import hashlib
import hmac
import json
import logging
from datetime import datetime, timezone
from decimal import Decimal

from fastapi import APIRouter, HTTPException, Header, Request
from pydantic import BaseModel, Field, ValidationError
from sqlalchemy import select, func
from typing import Optional
from uuid import UUID

from packages.common.src.database import AsyncSessionLocal
from packages.common.src.models import (
    AlgoApiKey, TradingAccount, Instrument, Position, PositionStatus,
)
from packages.common.src.schemas import PlaceOrderRequest, ClosePositionRequest
from packages.common.src.rate_limit import rate_limit_http, client_ip_for_inet
from ..services import trading_service

logger = logging.getLogger("algo_connector")
router = APIRouter()


def _hash_secret(raw: str) -> str:
    """SHA-256 hash for fast lookup (bcrypt is overkill for API secrets)."""
    return hashlib.sha256(raw.encode()).hexdigest()


class AlgoTradeRequest(BaseModel):
    action: str = Field(..., pattern="^(BUY|SELL|CLOSE)$")
    symbol: str
    volume: Optional[float] = None
    sl: Optional[float] = None
    tp: Optional[float] = None
    comment: Optional[str] = None
    #: CLOSE only. Closes exactly this position instead of every open one on
    #: the symbol.
    #:
    #: Without it, two bots trading the same symbol on one account close each
    #: other's positions — which made the connector unusable for anything
    #: running more than one strategy. Optional so every existing bot keeps
    #: its current behaviour unchanged.
    position_id: Optional[str] = None


async def _authenticate(x_api_key: str, x_api_secret: str, db) -> tuple[AlgoApiKey, TradingAccount]:
    if not x_api_key or not x_api_secret:
        raise HTTPException(status_code=401, detail="Missing X-Api-Key or X-Api-Secret")
    secret_hash = _hash_secret(x_api_secret)
    result = await db.execute(
        select(AlgoApiKey).where(
            AlgoApiKey.api_key == x_api_key,
            AlgoApiKey.is_active == True,
        )
    )
    key_row = result.scalar_one_or_none()
    # Constant-time compare so response timing can't leak how much of the hash matched.
    if not key_row or not hmac.compare_digest(str(key_row.secret_hash or ""), secret_hash):
        raise HTTPException(status_code=401, detail="Invalid API credentials")
    # A banned / blocked / suspended owner must not keep trading through a bot
    # key — web sessions already enforce this per request (get_current_user), the
    # API-key path never did.
    from packages.common.src.auth import _get_user_status, _BLOCKED_USER_STATUSES
    owner_status = await _get_user_status(key_row.user_id)
    if owner_status is None or owner_status in _BLOCKED_USER_STATUSES:
        raise HTTPException(status_code=403, detail="Account is disabled")
    account = await db.get(TradingAccount, key_row.account_id)
    if not account or not account.is_active:
        raise HTTPException(status_code=403, detail="Trading account is inactive")
    key_row.last_used_at = datetime.now(timezone.utc)
    return key_row, account


@router.post("/trade")
async def algo_trade(
    body: AlgoTradeRequest,
    request: Request,
    x_api_key: str = Header(default="", alias="X-Api-Key"),
    x_api_secret: str = Header(default="", alias="X-Api-Secret"),
):
    # Same bucket size as the web order endpoint — a retry-looping bot hits
    # the cap instead of hammering the execution path.
    rate_limit_http(request, "algo-trade", 120, 60.0)

    async with AsyncSessionLocal() as db:
        key_row, account = await _authenticate(x_api_key, x_api_secret, db)

        symbol = body.symbol.upper()
        action = body.action.upper()

        if action in ("BUY", "SELL"):
            if not body.volume or body.volume <= 0:
                raise HTTPException(status_code=400, detail="volume required for BUY/SELL")
            result = await _open_trade(body, symbol, account, key_row, request, db)
        elif body.position_id:
            result = await _close_one(body.position_id, symbol, account, key_row, db)
        else:
            result = await _close_trades(symbol, account, key_row, db)

        await db.commit()
        return result


@router.get("/account")
async def algo_account(
    x_api_key: str = Header(default="", alias="X-Api-Key"),
    x_api_secret: str = Header(default="", alias="X-Api-Secret"),
):
    """Return balance, equity, margin and leverage for the linked trading account."""
    async with AsyncSessionLocal() as db:
        key_row, account = await _authenticate(x_api_key, x_api_secret, db)

        open_q = await db.execute(
            select(func.count(Position.id)).where(
                Position.account_id == account.id,
                Position.status == PositionStatus.OPEN,
            )
        )
        open_count = int(open_q.scalar() or 0)

        await db.commit()

        zero = Decimal("0")
        return {
            "account": account.account_number,
            "currency": account.currency or "USD",
            "leverage": int(account.leverage or 100),
            "balance": float(account.balance or zero),
            "credit": float(account.credit or zero),
            "equity": float(account.equity or zero),
            "margin_used": float(account.margin_used or zero),
            "free_margin": float(account.free_margin or zero),
            "margin_level": float(account.margin_level or zero),
            "is_demo": bool(account.is_demo),
            "open_positions": open_count,
        }


@router.get("/positions")
async def algo_positions(
    x_api_key: str = Header(default="", alias="X-Api-Key"),
    x_api_secret: str = Header(default="", alias="X-Api-Secret"),
):
    """Every open position on the account this key is bound to.

    `/account` reports a count and nothing else, which is not enough for a bot
    that has to reconcile its own book against the broker's — and a bot with no
    way to ask "what am I actually holding" has to trust its own records after
    a restart, a missed response or a stop it never saw fire.

    Live prices and floating P&L come from the same call the web platform's
    own positions table uses, so the two cannot drift apart.
    """
    async with AsyncSessionLocal() as db:
        key_row, account = await _authenticate(x_api_key, x_api_secret, db)

        positions = await trading_service.list_positions(
            account_id=account.id, user_id=account.user_id, status="open", db=db,
        )
        await db.commit()

        return {
            "positions": [
                {
                    "position_id": p["id"],
                    "symbol": p["symbol"],
                    "side": p["side"],
                    "lots": p["lots"],
                    "open_price": p["open_price"],
                    # Null when the feed has not ticked since the position
                    # opened — the bot should fall back to open_price rather
                    # than treat it as zero.
                    "current_price": p["current_price"],
                    "stop_loss": p["stop_loss"],
                    "take_profit": p["take_profit"],
                    "swap": p["swap"],
                    "commission": p["commission"],
                    "profit": p["profit"],
                    "comment": p.get("comment") or "",
                    "opened_at": p["created_at"],
                }
                for p in positions
            ],
            "count": len(positions),
            "account": account.account_number,
        }


async def _open_trade(
    body: AlgoTradeRequest, symbol: str, account: TradingAccount,
    key_row: AlgoApiKey, request: Request, db,
) -> dict:
    """Open a market order via the canonical place_order path (commission,
    margin lock, market hours, stale-tick guard, IB, A-book — all included)."""
    try:
        req = PlaceOrderRequest(
            account_id=account.id,
            symbol=symbol,
            order_type="market",
            side=body.action.lower(),
            lots=Decimal(str(body.volume)),
            stop_loss=Decimal(str(body.sl)) if body.sl else None,
            take_profit=Decimal(str(body.tp)) if body.tp else None,
            comment=body.comment or f"Algo [{key_row.label or key_row.api_key[:12]}]",
        )
    except ValidationError as e:
        # Schema bounds (e.g. lots ∈ (0, 100]) — surface as a 400, not a 500.
        first = e.errors()[0] if e.errors() else {}
        raise HTTPException(
            status_code=400,
            detail=f"Invalid trade request: {first.get('loc', ('?',))[-1]} {first.get('msg', 'invalid')}",
        )

    result = await trading_service.place_order(
        req=req,
        request=request,
        user_id=account.user_id,
        ip_address=client_ip_for_inet(request),
        db=db,
    )
    key_row.trades_count = (key_row.trades_count or 0) + 1

    logger.info(
        "[ALGO] %s %s %.2f lots @ %s on %s (key=%s)",
        body.action, symbol, float(req.lots), result.get("filled_price"),
        account.account_number, key_row.api_key[:12],
    )
    # Keep the historical algo response shape for existing bots.
    return {
        "status": result.get("status", "filled"),
        "action": body.action,
        "symbol": symbol,
        "lots": result.get("lots"),
        "price": result.get("filled_price"),
        "commission": result.get("commission"),
        "position_id": result.get("position_id"),
        "order_id": result.get("id"),
        "account": account.account_number,
    }


async def _close_one(
    position_id: str, symbol: str, account: TradingAccount, key_row: AlgoApiKey, db
) -> dict:
    """Close exactly one position, leaving its siblings on the symbol alone.

    The account check is not redundant with the one inside
    `trading_service.close_position`: that one proves the position belongs to
    the *user*, and a user may hold several trading accounts. An API key is
    bound to one account, so a key must not be able to reach a position on
    another of its owner's accounts.
    """
    try:
        pid = UUID(str(position_id))
    except (ValueError, AttributeError):
        raise HTTPException(status_code=400, detail="position_id is not a valid id")

    pos = (await db.execute(
        select(Position).where(Position.id == pid)
    )).scalar_one_or_none()

    # Gone, someone else's, or already closed all answer the same question the
    # bot asked — "is this position still open on my account" — with no. A bot
    # that is told closing failed will retry forever against a position that
    # no longer exists.
    if pos is None or pos.account_id != account.id:
        return {
            "status": "no_positions",
            "symbol": symbol,
            "account": account.account_number,
            "position_id": str(position_id),
            "message": "No such open position on this account",
        }

    try:
        res = await trading_service.close_position(
            pos.id, ClosePositionRequest(), user_id=account.user_id, db=db,
            close_reason_override="algo_close",
        )
    except HTTPException as e:
        # 400 "not open" and 409 "already being closed" both mean the SL/TP
        # engine, a manual close or a retry got there first.
        if e.status_code in (400, 409):
            return {
                "status": "no_positions",
                "symbol": symbol,
                "account": account.account_number,
                "position_id": str(pos.id),
                "message": "Position was already closed",
            }
        raise

    key_row.trades_count = (key_row.trades_count or 0) + 1
    profit = Decimal(str(res.get("profit", 0)))

    logger.info(
        "[ALGO] Closed position %s (%s) on %s (P/L: %s)",
        pos.id, symbol, account.account_number, profit,
    )
    return {
        "status": "closed",
        "symbol": symbol,
        "account": account.account_number,
        "position_id": str(pos.id),
        "closed_count": 1,
        "close_price": float(res["close_price"]) if res.get("close_price") is not None else None,
        "total_profit": float(profit),
    }


async def _close_trades(symbol: str, account: TradingAccount, key_row: AlgoApiKey, db) -> dict:
    """Close all open positions for symbol via the canonical close path."""
    pos_q = await db.execute(
        select(Position.id).join(Instrument).where(
            Position.account_id == account.id,
            Position.status == PositionStatus.OPEN,
            Instrument.symbol == symbol,
        )
    )
    position_ids = [row[0] for row in pos_q.all()]

    if not position_ids:
        return {
            "status": "no_positions",
            "symbol": symbol,
            "account": account.account_number,
            "message": f"No open {symbol} positions to close",
        }

    closed_count = 0
    total_profit = Decimal("0")
    errors: list[str] = []
    for pid in position_ids:
        try:
            res = await trading_service.close_position(
                pid, ClosePositionRequest(), user_id=account.user_id, db=db,
                close_reason_override="algo_close",
            )
            closed_count += 1
            total_profit += Decimal(str(res.get("profit", 0)))
        except HTTPException as e:
            # 409 = raced with SL/TP engine or a manual close — already closed,
            # not an error for the bot. Anything else is reported per position.
            if e.status_code != 409:
                errors.append(f"{pid}: {e.detail}")

    key_row.trades_count = (key_row.trades_count or 0) + closed_count

    logger.info(
        "[ALGO] Closed %d %s positions on %s (P/L: %s)",
        closed_count, symbol, account.account_number, total_profit,
    )
    out = {
        "status": "closed" if closed_count else "failed",
        "symbol": symbol,
        "account": account.account_number,
        "closed_count": closed_count,
        "total_profit": float(total_profit),
    }
    if errors:
        out["errors"] = errors
    return out
